ENABLE_WAIT_RESULT=true
REDIS_HOST=judge0-redis
REDIS_PORT=6379
REDIS_PASSWORD=judge0-local-redis-password
POSTGRES_HOST=judge0-db
POSTGRES_PORT=5432
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0-local-postgres-password
AUTHN_HEADER=
AUTHN_TOKEN=
AUTHZ_HEADER=
AUTHZ_TOKEN=
ALLOW_ORIGIN=
CPU_TIME_LIMIT=5
MAX_CPU_TIME_LIMIT=15
CPU_EXTRA_TIME=1
WALL_TIME_LIMIT=10
MAX_WALL_TIME_LIMIT=20
MEMORY_LIMIT=128000
MAX_MEMORY_LIMIT=512000
ENABLE_NETWORK=false
