const javascriptStarter = `const fs = require('fs');

function solve(input) {
  // Viet loi giai o day. Tra ve chuoi ket qua cuoi cung.
  return '';
}

process.stdout.write(String(solve(fs.readFileSync(0, 'utf8'))));`;

export type CatalogCodeProblem = {
  title: string;
  slug: string;
  difficulty: 'EASY' | 'MEDIUM' | 'HARD';
  category: string;
  tags: string[];
  statement: string;
  inputFormat: string;
  outputFormat: string;
  constraintsText: string;
  examples: Array<{ input: string; output: string; explanation?: string }>;
  starterCode: Record<string, string>;
  solutionExplanation: string;
  timeLimitMs: number;
  memoryLimitMb: number;
  status: 'PUBLISHED';
  testCases: Array<{ input: string; expectedOutput: string; isHidden: boolean; order: number }>;
};

const starterCode = {
  JAVASCRIPT: javascriptStarter,
};

export const catalogCodeProblems: CatalogCodeProblem[] = [
  {
    title: 'Tổng hai số',
    slug: 'tong-hai-so',
    difficulty: 'EASY',
    category: 'MATH',
    tags: ['basic', 'input-output', 'math'],
    statement: 'Đọc hai số nguyên a, b và in ra tổng của chúng.',
    inputFormat: 'Một dòng gồm hai số nguyên a và b.',
    outputFormat: 'Một số nguyên là a + b.',
    constraintsText: '-10^9 <= a, b <= 10^9.',
    examples: [{ input: '2 3', output: '5' }],
    starterCode,
    solutionExplanation: 'Tách input theo khoảng trắng, ép số và cộng hai phần tử đầu tiên.',
    timeLimitMs: 1000,
    memoryLimitMb: 128,
    status: 'PUBLISHED',
    testCases: [
      { input: '2 3', expectedOutput: '5', isHidden: false, order: 1 },
      { input: '-5 13', expectedOutput: '8', isHidden: true, order: 2 },
    ],
  },
  {
    title: 'Đếm nguyên âm',
    slug: 'dem-nguyen-am',
    difficulty: 'EASY',
    category: 'STRING',
    tags: ['string', 'counting', 'vietnamese'],
    statement: 'Đếm số nguyên âm tiếng Anh trong chuỗi. Không phân biệt chữ hoa/thường.',
    inputFormat: 'Một dòng văn bản bất kỳ.',
    outputFormat: 'Một số nguyên là số ký tự thuộc tập a, e, i, o, u.',
    constraintsText: 'Độ dài chuỗi không quá 10^5 ký tự.',
    examples: [{ input: 'MentorMind AI', output: '5' }],
    starterCode,
    solutionExplanation: 'Duyệt từng ký tự sau khi lower-case và kiểm tra thuộc tập nguyên âm.',
    timeLimitMs: 1000,
    memoryLimitMb: 128,
    status: 'PUBLISHED',
    testCases: [
      { input: 'MentorMind AI', expectedOutput: '5', isHidden: false, order: 1 },
      { input: 'Truong hoc online', expectedOutput: '6', isHidden: true, order: 2 },
    ],
  },
  {
    title: 'Đảo ngược thứ tự từ',
    slug: 'dao-nguoc-thu-tu-tu',
    difficulty: 'EASY',
    category: 'STRING',
    tags: ['string', 'array', 'split'],
    statement: 'Cho một câu, hãy đảo ngược thứ tự các từ và giữ nguyên nội dung từng từ.',
    inputFormat: 'Một dòng chứa các từ cách nhau bằng một hoặc nhiều khoảng trắng.',
    outputFormat: 'Các từ sau khi đảo thứ tự, cách nhau bằng đúng một khoảng trắng.',
    constraintsText: 'Số từ không quá 10^4.',
    examples: [{ input: 'xin chao mentor', output: 'mentor chao xin' }],
    starterCode,
    solutionExplanation: 'Trim chuỗi, split theo regex khoảng trắng, reverse rồi join lại.',
    timeLimitMs: 1000,
    memoryLimitMb: 128,
    status: 'PUBLISHED',
    testCases: [
      { input: 'xin chao mentor', expectedOutput: 'mentor chao xin', isHidden: false, order: 1 },
      { input: 'mot hai ba bon', expectedOutput: 'bon ba hai mot', isHidden: true, order: 2 },
    ],
  },
  {
    title: 'FizzBuzz rút gọn',
    slug: 'fizzbuzz-rut-gon',
    difficulty: 'EASY',
    category: 'LOOP',
    tags: ['loop', 'condition', 'classic'],
    statement: 'In dãy từ 1 đến n. Số chia hết cho 3 in Fizz, chia hết cho 5 in Buzz, chia hết cho cả hai in FizzBuzz.',
    inputFormat: 'Một số nguyên n.',
    outputFormat: 'Một dòng gồm n token cách nhau bằng khoảng trắng.',
    constraintsText: '1 <= n <= 10^5.',
    examples: [{ input: '15', output: '1 2 Fizz 4 Buzz Fizz 7 8 Fizz Buzz 11 Fizz 13 14 FizzBuzz' }],
    starterCode,
    solutionExplanation: 'Duyệt i từ 1 đến n và xét điều kiện chia hết cho 15, 3, 5 theo thứ tự.',
    timeLimitMs: 1000,
    memoryLimitMb: 128,
    status: 'PUBLISHED',
    testCases: [
      {
        input: '15',
        expectedOutput: '1 2 Fizz 4 Buzz Fizz 7 8 Fizz Buzz 11 Fizz 13 14 FizzBuzz',
        isHidden: false,
        order: 1,
      },
      { input: '5', expectedOutput: '1 2 Fizz 4 Buzz', isHidden: true, order: 2 },
    ],
  },
  {
    title: 'Kiểm tra palindrome',
    slug: 'kiem-tra-palindrome',
    difficulty: 'EASY',
    category: 'STRING',
    tags: ['string', 'two-pointers', 'normalize'],
    statement: 'Kiểm tra chuỗi có phải palindrome sau khi bỏ ký tự không phải chữ/số và không phân biệt hoa thường.',
    inputFormat: 'Một dòng văn bản.',
    outputFormat: 'In true nếu là palindrome, ngược lại in false.',
    constraintsText: 'Độ dài chuỗi không quá 10^5.',
    examples: [{ input: 'A man a plan a canal Panama', output: 'true' }],
    starterCode,
    solutionExplanation: 'Chuẩn hóa chuỗi còn chữ/số lowercase rồi dùng hai con trỏ hoặc so với chuỗi đảo.',
    timeLimitMs: 1000,
    memoryLimitMb: 128,
    status: 'PUBLISHED',
    testCases: [
      { input: 'A man a plan a canal Panama', expectedOutput: 'true', isHidden: false, order: 1 },
      { input: 'MentorMind', expectedOutput: 'false', isHidden: true, order: 2 },
    ],
  },
  {
    title: 'Tần suất từ',
    slug: 'tan-suat-tu',
    difficulty: 'EASY',
    category: 'HASH_MAP',
    tags: ['hash-map', 'string', 'frequency'],
    statement: 'Đếm số lần xuất hiện của từng từ, không phân biệt hoa thường, rồi in theo thứ tự alphabet.',
    inputFormat: 'Một dòng gồm nhiều từ cách nhau bằng khoảng trắng.',
    outputFormat: 'Các cặp word:count cách nhau bằng khoảng trắng.',
    constraintsText: 'Tổng số từ không quá 10^5.',
    examples: [{ input: 'ai ai code mentor ai', output: 'ai:3 code:1 mentor:1' }],
    starterCode,
    solutionExplanation: 'Dùng Map để đếm, sort key tăng dần rồi format từng cặp.',
    timeLimitMs: 1000,
    memoryLimitMb: 128,
    status: 'PUBLISHED',
    testCases: [
      { input: 'ai ai code mentor ai', expectedOutput: 'ai:3 code:1 mentor:1', isHidden: false, order: 1 },
      { input: 'b a b c a b', expectedOutput: 'a:2 b:3 c:1', isHidden: true, order: 2 },
    ],
  },
  {
    title: 'Two Sum trả về chỉ số',
    slug: 'two-sum-tra-ve-chi-so',
    difficulty: 'MEDIUM',
    category: 'HASH_MAP',
    tags: ['hash-map', 'array', 'interview'],
    statement: 'Cho target và mảng số nguyên, tìm hai chỉ số i j sao cho nums[i] + nums[j] = target. Luôn có đúng một đáp án.',
    inputFormat: 'Dòng 1 là target. Dòng 2 là mảng số nguyên cách nhau bằng khoảng trắng.',
    outputFormat: 'Hai chỉ số i j theo thứ tự tăng dần, index bắt đầu từ 0.',
    constraintsText: '2 <= nums.length <= 10^5.',
    examples: [{ input: '9\n2 7 11 15', output: '0 1' }],
    starterCode,
    solutionExplanation: 'Duyệt mảng, lưu value -> index trong Map và tìm complement target - value.',
    timeLimitMs: 1200,
    memoryLimitMb: 128,
    status: 'PUBLISHED',
    testCases: [
      { input: '9\n2 7 11 15', expectedOutput: '0 1', isHidden: false, order: 1 },
      { input: '6\n3 2 4', expectedOutput: '1 2', isHidden: true, order: 2 },
    ],
  },
  {
    title: 'Ngoặc hợp lệ',
    slug: 'ngoac-hop-le',
    difficulty: 'MEDIUM',
    category: 'STACK',
    tags: ['stack', 'string', 'interview'],
    statement: 'Kiểm tra chuỗi ngoặc gồm (), [], {} có hợp lệ hay không.',
    inputFormat: 'Một dòng chỉ chứa các ký tự ngoặc.',
    outputFormat: 'In true nếu hợp lệ, ngược lại in false.',
    constraintsText: 'Độ dài chuỗi không quá 10^5.',
    examples: [{ input: '({[]})', output: 'true' }],
    starterCode,
    solutionExplanation: 'Dùng stack, đẩy ngoặc mở và so khớp khi gặp ngoặc đóng.',
    timeLimitMs: 1000,
    memoryLimitMb: 128,
    status: 'PUBLISHED',
    testCases: [
      { input: '({[]})', expectedOutput: 'true', isHidden: false, order: 1 },
      { input: '([)]', expectedOutput: 'false', isHidden: true, order: 2 },
    ],
  },
  {
    title: 'Gộp khoảng thời gian',
    slug: 'gop-khoang-thoi-gian',
    difficulty: 'MEDIUM',
    category: 'INTERVAL',
    tags: ['interval', 'sorting', 'array'],
    statement: 'Cho các khoảng [start, end], hãy gộp các khoảng giao nhau hoặc chạm nhau.',
    inputFormat: 'Một dòng các khoảng dạng start end;start end;...',
    outputFormat: 'Các khoảng sau khi gộp, cùng định dạng start end;start end;...',
    constraintsText: 'Số khoảng không quá 10^5, start <= end.',
    examples: [{ input: '1 3;2 6;8 10;15 18', output: '1 6;8 10;15 18' }],
    starterCode,
    solutionExplanation: 'Sort theo start, dùng mảng kết quả và mở rộng end khi khoảng hiện tại giao/chạm khoảng cuối.',
    timeLimitMs: 1200,
    memoryLimitMb: 128,
    status: 'PUBLISHED',
    testCases: [
      { input: '1 3;2 6;8 10;15 18', expectedOutput: '1 6;8 10;15 18', isHidden: false, order: 1 },
      { input: '1 4;4 5', expectedOutput: '1 5', isHidden: true, order: 2 },
    ],
  },
  {
    title: 'Top K từ khóa',
    slug: 'top-k-tu-khoa',
    difficulty: 'MEDIUM',
    category: 'SORTING',
    tags: ['hash-map', 'sorting', 'nlp'],
    statement: 'Tìm K từ xuất hiện nhiều nhất. Nếu bằng tần suất, từ nào alphabet nhỏ hơn đứng trước.',
    inputFormat: 'Dòng 1 là K. Dòng 2 là danh sách từ cách nhau bằng khoảng trắng.',
    outputFormat: 'K từ khóa cách nhau bằng khoảng trắng.',
    constraintsText: '1 <= K <= số từ khác nhau <= 10^5.',
    examples: [{ input: '2\nai chatbot ai rag chatbot ai', output: 'ai chatbot' }],
    starterCode,
    solutionExplanation: 'Đếm bằng Map rồi sort theo count giảm dần, key tăng dần.',
    timeLimitMs: 1300,
    memoryLimitMb: 128,
    status: 'PUBLISHED',
    testCases: [
      { input: '2\nai chatbot ai rag chatbot ai', expectedOutput: 'ai chatbot', isHidden: false, order: 1 },
      { input: '3\nb a c a b b d', expectedOutput: 'b a c', isHidden: true, order: 2 },
    ],
  },
  {
    title: 'Rate limiter đơn giản',
    slug: 'rate-limiter-don-gian',
    difficulty: 'MEDIUM',
    category: 'SYSTEM_DESIGN',
    tags: ['queue', 'rate-limit', 'backend'],
    statement:
      'Mỗi user chỉ được phép có tối đa limit request trong cửa sổ window giây gần nhất. Với mỗi request, in ALLOW hoặc REJECT.',
    inputFormat: 'Dòng 1: limit window. Các dòng sau: timestamp userId, timestamp tăng dần.',
    outputFormat: 'Một dòng gồm kết quả của từng request, cách nhau bằng khoảng trắng.',
    constraintsText: 'Số request không quá 10^5. Request cũ có timestamp <= current - window không còn nằm trong cửa sổ.',
    examples: [{ input: '2 5\n1 a\n2 a\n3 a\n7 a\n8 a', output: 'ALLOW ALLOW REJECT ALLOW ALLOW' }],
    starterCode,
    solutionExplanation: 'Lưu queue timestamp theo user, loại timestamp hết hạn rồi kiểm tra độ dài queue.',
    timeLimitMs: 1500,
    memoryLimitMb: 128,
    status: 'PUBLISHED',
    testCases: [
      { input: '2 5\n1 a\n2 a\n3 a\n7 a\n8 a', expectedOutput: 'ALLOW ALLOW REJECT ALLOW ALLOW', isHidden: false, order: 1 },
      { input: '1 3\n1 u1\n2 u2\n3 u1\n4 u1', expectedOutput: 'ALLOW ALLOW REJECT ALLOW', isHidden: true, order: 2 },
    ],
  },
  {
    title: 'Tìm đường trong lưới',
    slug: 'tim-duong-trong-luoi',
    difficulty: 'MEDIUM',
    category: 'GRAPH',
    tags: ['bfs', 'grid', 'shortest-path'],
    statement: 'Cho lưới có S là điểm bắt đầu, E là điểm kết thúc, # là tường. Tìm số bước ngắn nhất từ S đến E.',
    inputFormat: 'Dòng 1: n m. n dòng tiếp theo là lưới.',
    outputFormat: 'Số bước ngắn nhất, hoặc -1 nếu không có đường.',
    constraintsText: '1 <= n, m <= 500.',
    examples: [{ input: '3 3\nS..\n.#.\n..E', output: '4' }],
    starterCode,
    solutionExplanation: 'Dùng BFS từ S với 4 hướng, dừng khi gặp E.',
    timeLimitMs: 1500,
    memoryLimitMb: 256,
    status: 'PUBLISHED',
    testCases: [
      { input: '3 3\nS..\n.#.\n..E', expectedOutput: '4', isHidden: false, order: 1 },
      { input: '2 2\nS#\n#E', expectedOutput: '-1', isHidden: true, order: 2 },
    ],
  },
  {
    title: 'Chuẩn hóa slug tiếng Việt',
    slug: 'chuan-hoa-slug-tieng-viet',
    difficulty: 'MEDIUM',
    category: 'STRING',
    tags: ['slug', 'unicode', 'seo'],
    statement: 'Chuyển tiêu đề tiếng Việt thành slug SEO: bỏ dấu, lowercase, thay cụm không phải chữ/số bằng dấu gạch ngang.',
    inputFormat: 'Một dòng tiêu đề.',
    outputFormat: 'Slug đã chuẩn hóa.',
    constraintsText: 'Độ dài tiêu đề không quá 10^4.',
    examples: [{ input: 'Lộ trình AI căn bản!', output: 'lo-trinh-ai-can-ban' }],
    starterCode,
    solutionExplanation: 'Dùng normalize NFD để bỏ dấu, xử lý riêng đ/Đ, regex thay ký tự không hợp lệ bằng -.',
    timeLimitMs: 1000,
    memoryLimitMb: 128,
    status: 'PUBLISHED',
    testCases: [
      { input: 'Lộ trình AI căn bản!', expectedOutput: 'lo-trinh-ai-can-ban', isHidden: false, order: 1 },
      { input: '  MentorMind: Học Code 101  ', expectedOutput: 'mentormind-hoc-code-101', isHidden: true, order: 2 },
    ],
  },
  {
    title: 'Điểm trung bình học viên',
    slug: 'diem-trung-binh-hoc-vien',
    difficulty: 'MEDIUM',
    category: 'DATA_PROCESSING',
    tags: ['map', 'aggregation', 'formatting'],
    statement: 'Cho nhiều dòng tên và điểm. Tính điểm trung bình mỗi học viên và in theo thứ tự alphabet.',
    inputFormat: 'Mỗi dòng gồm name score. name không chứa khoảng trắng.',
    outputFormat: 'Các cặp name:average cách nhau bằng khoảng trắng, average có đúng 2 chữ số thập phân.',
    constraintsText: 'Số dòng không quá 10^5, 0 <= score <= 10.',
    examples: [{ input: 'An 8\nBinh 7\nAn 10', output: 'An:9.00 Binh:7.00' }],
    starterCode,
    solutionExplanation: 'Tích lũy tổng và số lượng theo tên, sort tên và dùng toFixed(2).',
    timeLimitMs: 1200,
    memoryLimitMb: 128,
    status: 'PUBLISHED',
    testCases: [
      { input: 'An 8\nBinh 7\nAn 10', expectedOutput: 'An:9.00 Binh:7.00', isHidden: false, order: 1 },
      { input: 'Lan 9\nLan 8\nMinh 6\nAn 10', expectedOutput: 'An:10.00 Lan:8.50 Minh:6.00', isHidden: true, order: 2 },
    ],
  },
  {
    title: 'LRU Cache mini',
    slug: 'lru-cache-mini',
    difficulty: 'HARD',
    category: 'DESIGN',
    tags: ['lru', 'map', 'linked-list', 'cache'],
    statement:
      'Mô phỏng LRU cache. PUT key value thêm/cập nhật key. GET key trả value hoặc -1. Khi quá capacity, xóa key ít được dùng gần đây nhất.',
    inputFormat: 'Dòng 1 là capacity. Các dòng sau là PUT key value hoặc GET key.',
    outputFormat: 'Một dòng gồm kết quả của các lệnh GET, cách nhau bằng khoảng trắng.',
    constraintsText: 'Số lệnh không quá 10^5. Capacity >= 1.',
    examples: [{ input: '2\nPUT a 1\nPUT b 2\nGET a\nPUT c 3\nGET b\nGET c', output: '1 -1 3' }],
    starterCode,
    solutionExplanation: 'Dùng Map giữ thứ tự insertion; mỗi GET/PUT thành công xóa rồi set lại key để đưa về mới nhất.',
    timeLimitMs: 1500,
    memoryLimitMb: 128,
    status: 'PUBLISHED',
    testCases: [
      { input: '2\nPUT a 1\nPUT b 2\nGET a\nPUT c 3\nGET b\nGET c', expectedOutput: '1 -1 3', isHidden: false, order: 1 },
      { input: '1\nPUT x 10\nPUT y 20\nGET x\nGET y', expectedOutput: '-1 20', isHidden: true, order: 2 },
    ],
  },
  {
    title: 'Dijkstra giao hàng',
    slug: 'dijkstra-giao-hang',
    difficulty: 'HARD',
    category: 'GRAPH',
    tags: ['dijkstra', 'shortest-path', 'priority-queue'],
    statement: 'Cho đồ thị có trọng số dương, tìm chi phí ngắn nhất từ start đến target.',
    inputFormat: 'Dòng 1: n m start target. m dòng tiếp theo: u v w, cạnh có hướng từ u đến v.',
    outputFormat: 'Chi phí ngắn nhất, hoặc -1 nếu không đi được.',
    constraintsText: '1 <= n <= 10^5, 1 <= m <= 2*10^5, 1 <= w <= 10^9.',
    examples: [{ input: '4 4 1 4\n1 2 5\n1 3 2\n3 2 1\n2 4 3', output: '6' }],
    starterCode,
    solutionExplanation: 'Dùng adjacency list và min-heap để triển khai Dijkstra.',
    timeLimitMs: 2500,
    memoryLimitMb: 256,
    status: 'PUBLISHED',
    testCases: [
      { input: '4 4 1 4\n1 2 5\n1 3 2\n3 2 1\n2 4 3', expectedOutput: '6', isHidden: false, order: 1 },
      { input: '3 1 1 3\n1 2 7', expectedOutput: '-1', isHidden: true, order: 2 },
    ],
  },
  {
    title: 'Word Ladder rút gọn',
    slug: 'word-ladder-rut-gon',
    difficulty: 'HARD',
    category: 'GRAPH',
    tags: ['bfs', 'word-ladder', 'string'],
    statement:
      'Mỗi bước được đổi đúng một ký tự để biến start thành end, từ trung gian phải nằm trong dictionary. Tìm số từ trong chuỗi biến đổi ngắn nhất.',
    inputFormat: 'Dòng 1: start end. Dòng 2: dictionary cách nhau bằng dấu phẩy.',
    outputFormat: 'Độ dài chuỗi biến đổi ngắn nhất, hoặc 0 nếu không tồn tại.',
    constraintsText: 'Số từ không quá 5000, các từ cùng độ dài.',
    examples: [{ input: 'hit cog\nhot,dot,dog,lot,log,cog', output: '5' }],
    starterCode,
    solutionExplanation: 'BFS trên không gian từ; có thể tạo pattern h*t để tìm neighbor nhanh.',
    timeLimitMs: 2500,
    memoryLimitMb: 256,
    status: 'PUBLISHED',
    testCases: [
      { input: 'hit cog\nhot,dot,dog,lot,log,cog', expectedOutput: '5', isHidden: false, order: 1 },
      { input: 'hit cog\nhot,dot,dog,lot,log', expectedOutput: '0', isHidden: true, order: 2 },
    ],
  },
  {
    title: 'Kiểm tra lịch mentor',
    slug: 'kiem-tra-lich-mentor',
    difficulty: 'HARD',
    category: 'INTERVAL',
    tags: ['interval', 'schedule', 'sorting'],
    statement:
      'Cho danh sách lịch dạng HH:MM HH:MM. Hãy kiểm tra có buổi nào bị trùng giờ không. Nếu có, in buổi đầu tiên gây xung đột sau khi sort theo giờ bắt đầu.',
    inputFormat: 'Một dòng các khoảng dạng HH:MM HH:MM;HH:MM HH:MM;...',
    outputFormat: 'OK nếu không trùng, hoặc CONFLICT start-end.',
    constraintsText: 'Số khoảng không quá 10^5, thời gian trong cùng một ngày.',
    examples: [{ input: '09:00 10:00;10:00 11:00;10:30 12:00', output: 'CONFLICT 10:30-12:00' }],
    starterCode,
    solutionExplanation: 'Đổi HH:MM sang phút, sort theo start, kiểm tra start < end trước đó.',
    timeLimitMs: 1200,
    memoryLimitMb: 128,
    status: 'PUBLISHED',
    testCases: [
      { input: '09:00 10:00;10:00 11:00;10:30 12:00', expectedOutput: 'CONFLICT 10:30-12:00', isHidden: false, order: 1 },
      { input: '08:00 09:00;09:00 10:00;13:00 14:30', expectedOutput: 'OK', isHidden: true, order: 2 },
    ],
  },
  {
    title: 'Ghép chunk RAG theo ngân sách token',
    slug: 'ghep-chunk-rag-theo-ngan-sach-token',
    difficulty: 'HARD',
    category: 'AI_ENGINEERING',
    tags: ['rag', 'greedy', 'token-budget'],
    statement:
      'Cho ngân sách token và danh sách chunk theo thứ tự ưu tiên. Chọn các chunk theo thứ tự đã cho nếu còn đủ ngân sách, bỏ qua chunk quá lớn.',
    inputFormat: 'Dòng 1 là maxTokens. Các dòng sau dạng tokens|title.',
    outputFormat: 'Title của các chunk được chọn, cách nhau bằng khoảng trắng.',
    constraintsText: 'Số chunk không quá 10^5.',
    examples: [{ input: '10\n4|intro\n7|deep\n3|summary\n2|faq', output: 'intro summary faq' }],
    starterCode,
    solutionExplanation: 'Duyệt chunk theo thứ tự, nếu used + tokens <= maxTokens thì chọn.',
    timeLimitMs: 1200,
    memoryLimitMb: 128,
    status: 'PUBLISHED',
    testCases: [
      { input: '10\n4|intro\n7|deep\n3|summary\n2|faq', expectedOutput: 'intro summary faq', isHidden: false, order: 1 },
      { input: '5\n6|too_big\n2|a\n3|b\n1|c', expectedOutput: 'a b', isHidden: true, order: 2 },
    ],
  },
  {
    title: 'Tối ưu phân bổ mentor',
    slug: 'toi-uu-phan-bo-mentor',
    difficulty: 'HARD',
    category: 'SUPER_HARD',
    tags: ['optimization', 'matching', 'dynamic-programming', 'mentor'],
    statement:
      'Có n mentor, m học viên. Mỗi mentor có capacity, score[i][j] là độ phù hợp mentor i với học viên j. Mỗi học viên được gán tối đa một mentor. Tối đa hóa tổng score.',
    inputFormat: 'Dòng 1: n m. Dòng 2: n capacity. n dòng tiếp theo, mỗi dòng có m score.',
    outputFormat: 'Tổng score lớn nhất.',
    constraintsText: '1 <= n <= 8, 1 <= m <= 16, capacity tổng có thể nhỏ hơn m.',
    examples: [{ input: '2 3\n1 1\n9 8 1\n6 7 5', output: '16' }],
    starterCode,
    solutionExplanation: 'Dùng DP bitmask theo mentor và tập học viên đã gán, thử chọn tổ hợp học viên trong capacity của từng mentor.',
    timeLimitMs: 3000,
    memoryLimitMb: 256,
    status: 'PUBLISHED',
    testCases: [
      { input: '2 3\n1 1\n9 8 1\n6 7 5', expectedOutput: '16', isHidden: false, order: 1 },
      { input: '1 3\n2\n4 9 5', expectedOutput: '14', isHidden: true, order: 2 },
    ],
  },
  {
    title: 'Tìm K vector gần nhất',
    slug: 'tim-k-vector-gan-nhat',
    difficulty: 'HARD',
    category: 'SUPER_HARD',
    tags: ['vector-search', 'cosine-similarity', 'ai', 'ranking'],
    statement:
      'Cho query vector và danh sách document vector. Tính cosine similarity, trả về K id gần nhất. Nếu bằng điểm, id alphabet nhỏ hơn đứng trước.',
    inputFormat: 'Dòng 1 là K. Dòng 2 là query vector. Các dòng sau: id và các thành phần vector.',
    outputFormat: 'K id cách nhau bằng khoảng trắng.',
    constraintsText: 'Số vector không quá 10^4, số chiều không quá 256.',
    examples: [{ input: '2\n0 1\na 0 1\nb 1 0\nc 0.7 0.7', output: 'a c' }],
    starterCode,
    solutionExplanation: 'Tính dot/(normA*normB), sort theo similarity giảm dần rồi id tăng dần.',
    timeLimitMs: 2500,
    memoryLimitMb: 256,
    status: 'PUBLISHED',
    testCases: [
      { input: '2\n0 1\na 0 1\nb 1 0\nc 0.7 0.7', expectedOutput: 'a c', isHidden: false, order: 1 },
      { input: '3\n1 1\nx 1 0\ny 0 1\nz 2 2\na 1 1', expectedOutput: 'a z x', isHidden: true, order: 2 },
    ],
  },
];
